# from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .nodes import COMBINED_MAPPINGS

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}
for k, v in COMBINED_MAPPINGS.items():
    NODE_CLASS_MAPPINGS[k] = v[0]
    NODE_DISPLAY_NAME_MAPPINGS[k] = v[1]

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']